export const GET_USER_AUTH = 'GET_USER_AUTH';
export const SET_USER_AUTH = 'SET_USER_AUTH';

export const GET_CURRENT_USER = 'GET_USER';
export const GET_USERS = 'GET_USERS';
export const GET_SUGGESTED_USERS = 'GET_SUGGESTED_USERS';

export const GET_TRENDS = 'GET_TRENDS';

export const SET_STATUS_LOADING = 'SET_STATUS_LOADING';
export const GET_HOME_TIMELINE = 'GET_HOME_TIMELINE';
export const GET_NEW_HOME_TIMELINE = 'GET_NEW_HOME_TIMELINE';
export const GET_USER_TIMELINE = 'GET_USER_TIMELINE';
export const GET_NEW_USER_TIMELINE = 'GET_NEW_USER_TIMELINE';
export const ADD_STATUS_ACTION = 'ADD_STATUS_ACTION';
export const REMOVE_STATUS_ACTION = 'REMOVE_STATUS_ACTION';
